#!/usr/bin/env python

from ceburasko.binary_id import binary_id


if __name__ == "__main__":
    import sys
    for filename in sys.argv[1:]:
        try:
            print "%s %s" % (binary_id(filename), filename)
        except Exception as e:
            print "%s: %s" % (sys.argv[0], e)
