#!/usr/bin/env python

from ceburasko.binary_id import binary_id
from ceburasko.api import upload_binary_info
import os
import json
from argparse import ArgumentParser


def is_exe(path):
    if path.lower().endswith('.exe'):
        return True
    return os.path.isfile(path) and os.access(path, os.X_OK)


def main():
    parser = ArgumentParser()
    parser.add_argument('version', help='builded version')
    parser.add_argument('basedir', help='directory with builded binaries')
    parser.add_argument('url', help='Ceburasko project URL')
    args = parser.parse_args()
    basedir = args.basedir

    ids = {}
    for directory, _, files in os.walk(basedir):
        for relative_filename in files:
            filename = os.path.join(directory, relative_filename)
            if is_exe(filename):
                component = os.path.relpath(filename, basedir)
                id = binary_id(filename)
                if id in ids:
                    ids[id].append(component)
                else:
                    ids[id] = [component]
    print upload_binary_info(version=args.version, ids=ids, project_url=args.url).read()

if __name__ == '__main__':
    main()
