#!/usr/bin/env python

from argparse import ArgumentParser
from ceburasko.api import upload_accidents
from ceburasko.log_parsers import accident_from_coredump
import os

if __name__ == "__main__":
    parser = ArgumentParser()
    parser.add_argument(
        '--timeout',
        help='Operation timeout',
        type=int,
        default=300,
    )
    parser.add_argument(
        'coredump',
        help='path to coredump',
    )
    parser.add_argument(
        'project_url',
        help='Ceburasko project URL for upload crash stack',
    )
    args = parser.parse_args()

    accident = accident_from_coredump(args.coredump)
    upload_accidents(accident, args.project_url)
    os.unlink(args.coredump)
