#!/usr/bin/env python

from argparse import ArgumentParser
from ceburasko.api import upload_accidents, UploadDataError
from ceburasko.log_parsers import accident_from_coredump
import os

if __name__ == "__main__":
    parser = ArgumentParser()
    parser.add_argument(
        '--timeout',
        help='Operation timeout',
        type=int,
        default=300,
    )
    parser.add_argument(
        'coredump',
        help='path to coredump',
    )
    parser.add_argument(
        'project_url',
        help='Ceburasko project URL for upload crash stack',
    )
    args = parser.parse_args()

    should_cleanup = True
    stdout = args.coredump.replace('.core', '.stdout')
    stderr = args.coredump.replace('.core', '.stderr')
    try:
        accident = accident_from_coredump(args.coredump)
        upload_accidents(accident, args.project_url, [stdout, stderr], args.timeout)
    except UploadDataError as e:
        should_cleanup = False
    finally:
        if should_cleanup:
            for filename in (args.coredump, stdout, stderr):
                try:
                    os.unlink(filename)
                except OSError as e:
                    pass
