#!/usr/bin/env python

from argparse import ArgumentParser
from ceburasko.api import upload_errors
from ceburasko.log_parsers import errors_from_gdb_log

if __name__ == "__main__":
    parser = ArgumentParser()
    parser.add_argument('gdblog',
        help = 'log from gdb')
    parser.add_argument('project_url',
        help = 'Ceburasko project URL for upload crash stack')
    args = parser.parse_args()

    errors = errors_from_gdb_log(args.gdblog)
    upload_errors(errors, args.project_url)
