#!/usr/bin/env python

import sys
import subprocess
import os
import hashlib
import tempfile
import signal
from argparse import ArgumentParser
from ceburasko.binary_id import binary_id


def main():
    parser = ArgumentParser()
    parser.add_argument(
        '--valgrind-dir',
        help='Valgrind log output directory',
        default=None,
    )
    parser.add_argument(
        'program',
        help='Full path to your program',
    )
    parser.add_argument(
        'args',
        metavar='arg',
        nargs='*',
        help='Your program args',
    )
    args = parser.parse_args()

    binary_comment = binary_id(args.program)
    log_filename = tempfile.mkstemp(prefix='valgrind.', suffix='.log.part', dir=args.valgrind_dir)[1]

    valgrind = ['/usr/bin/valgrind']
    valgrind += ['--xml=yes', '--xml-file=%s' % log_filename]
    valgrind += ['--xml-user-comment=%s' % binary_comment]
    valgrind += [args.program] + args.args
    process = subprocess.Popen(valgrind)
    try:
        process.wait()
    except KeyboardInterrupt as ki:
        process.send_signal(signal.SIGINT)
        process.wait()
    os.rename(log_filename, log_filename.replace('.log.part', '.log.xml'))

if __name__ == '__main__':
    main()
