#!/usr/bin/env python

import sys
import subprocess
import os
import hashlib
import tempfile
import signal
from argparse import ArgumentParser
from ceburasko.binary_id import binary_id
from ceburasko.interruption_handler import InterruptionHandler


class MyInterruptionHandler(InterruptionHandler):
    def __init__(self, process, logfile, signum=signal.SIGINT):
        super(MyInterruptionHandler, self).__init__(signum)
        self.process = process
        self.logfile = logfile

    def on_signal(self, signum):
        if self.process.poll() is None:
            if os.name != 'nt':
                self.process.terminate()
            else:
                self.process.send_signal(signum)
        try:
            self.process.wait()
        except:
            pass
        os.rename(self.logfile, self.logfile.replace('.log.part', '.log.xml'))


def main():
    parser = ArgumentParser()
    parser.add_argument(
        '--valgrind-dir',
        help='Valgrind log output directory',
        default=None,
    )
    parser.add_argument(
        'program',
        help='Full path to your program',
    )
    parser.add_argument(
        'args',
        metavar='arg',
        nargs='*',
        help='Your program args',
    )
    args = parser.parse_args()

    binary_comment = binary_id(args.program)
    log_filename = tempfile.mkstemp(prefix='valgrind.', suffix='.log.part', dir=args.valgrind_dir)[1]

    valgrind = ['/usr/bin/valgrind']
    valgrind += ['--xml=yes', '--xml-file=%s' % log_filename]
    valgrind += ['--xml-user-comment=%s' % binary_comment]
    valgrind += [args.program] + args.args
    process = subprocess.Popen(valgrind)
    MyInterruptionHandler(process, log_filename)
    process.wait()
    os.rename(log_filename, log_filename.replace('.log.part', '.log.xml'))

if __name__ == '__main__':
    main()
