#!/usr/bin/env python

from ceburasko.binary_id import find_by_binary_id


if __name__ == "__main__":
    import sys
    for binary_id in sys.argv[1:]:
        filename = find_by_binary_id(binary_id)
        print "%s %s" % (binary_id, filename if filename else "-")
