#!/usr/bin/env python

from argparse import ArgumentParser
from ceburasko.api import upload_accidents, UploadDataError
from ceburasko.log_parsers import accidents_from_valgrind_log
import os

if __name__ == "__main__":
    parser = ArgumentParser()
    parser.add_argument(
        "--timeout",
        help="Operation timeout",
        type=int,
        default=300,
    )
    parser.add_argument(
        "xml",
        help="Valgrind XML log",
    )
    parser.add_argument(
        "project_url",
        help="Ceburasko project URL for upload crash stack",
    )
    args = parser.parse_args()

    should_cleanup = True
    stdout = args.xml.replace('.log.xml', '.stdout')
    stderr = args.xml.replace('.log.xml', '.stderr')
    try:
        accidents = accidents_from_valgrind_log(args.xml)
        upload_accidents(accidents, args.project_url, [stdout, stderr], args.timeout)
    except UploadDataError as e:
        should_cleanup = False
    finally:
        if should_cleanup:
            for filename in (args.xml, stdout, stderr):
                try:
                    os.unlink(filename)
                except OSError as e:
                    pass
